name: harmonyos-ncnn
on:
  push:
    branches:
      - master

env:
  OHOS_NDK_CMAKE: ${{ github.workspace }}/ohos-sdk/linux/native/build-tools/cmake/bin/cmake
  COMMON_CMAKE_OPTIONS: |
    -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/ohos-sdk/linux/native/build/cmake/ohos.toolchain.cmake \
    -DCMAKE_INSTALL_PREFIX=install \
    -DCMAKE_BUILD_TYPE=Release

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download OHOS SDK
        run: |
          wget https://repo.huaweicloud.com/harmonyos/os/4.0-Release/ohos-sdk-windows_linux-public.tar.gz
          tar -xf ohos-sdk-windows_linux-public.tar.gz
          cd ohos-sdk/linux
          unzip -q native-linux-x64-4.0.10.13-Release.zip

      - name: Build for multiple architectures
        run: |
          for ARCH in armeabi-v7a arm64-v8a x86_64; do
            mkdir build-$ARCH
            cd build-$ARCH
            ${{ env.OHOS_NDK_CMAKE }} ${{ env.COMMON_CMAKE_OPTIONS }} -DOHOS_ARCH="$ARCH" ${{ github.workspace }}
            ${{ env.OHOS_NDK_CMAKE }} --build . -j $(nproc)
            ${{ env.OHOS_NDK_CMAKE }} --build . --target install
            cd ..
          done

      - name: Package
        run: |
          mkdir -p ncnn-package/x86_64 ncnn-package/armeabi-v7a ncnn-package/arm64-v8a
          cp -rf build-x86_64/install/* ncnn-package/x86_64/
          cp -rf build-armeabi-v7a/install/* ncnn-package/armeabi-v7a/
          cp -rf build-arm64-v8a/install/* ncnn-package/arm64-v8a/
          zip -r ncnn-package.zip ncnn-package

      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: ncnn-package
          path: ncnn-package.zip
