name: harmonyos
on:
  push:
    branches:
      - master

env:
  OHOS_NDK_HOME: /path/to/ohos-sdk/linux/native
  OHOS_NDK_CMAKE: ${{ env.OHOS_NDK_HOME }}/build-tools/cmake/bin/cmake
  NCNN_CMAKE_OPTIONS: |
    -DCMAKE_TOOLCHAIN_FILE=${{ env.OHOS_NDK_HOME }}/build/cmake/ohos.toolchain.cmake \
    -DCMAKE_INSTALL_PREFIX=install \
    -DCMAKE_BUILD_TYPE=Release \
    -DNCNN_SIMPLEOMP=ON \
    -DNCNN_VULKAN=ON

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: setup-sdk
      run: |
        wget https://repo.huaweicloud.com/harmonyos/os/4.0-Release/ohos-sdk-linux-public.tar.gz
        tar -xf ohos-sdk-linux-public.tar.gz
        cd ohos-sdk/linux
        unzip -q native-linux-x64-4.0.10.13-Release.zip

    - name: build-armeabi-v7a
      run: |
        mkdir build-armeabi-v7a && cd build-armeabi-v7a
        ${{ env.OHOS_NDK_CMAKE }} ${{ env.NCNN_CMAKE_OPTIONS }} -DOHOS_ARCH="armeabi-v7a" ..
        ${{ env.OHOS_NDK_CMAKE }} --build . -j $(nproc)
        ${{ env.OHOS_NDK_CMAKE }} --build . --target install

    - name: build-arm64-v8a
      run: |
        mkdir build-arm64-v8a && cd build-arm64-v8a
        ${{ env.OHOS_NDK_CMAKE }} ${{ env.NCNN_CMAKE_OPTIONS }} -DOHOS_ARCH="arm64-v8a" ..
        ${{ env.OHOS_NDK_CMAKE }} --build . -j $(nproc)
        ${{ env.OHOS_NDK_CMAKE }} --build . --target install

    - name: build-x86_64
      run: |
        mkdir build-x86_64 && cd build-x86_64
        ${{ env.OHOS_NDK_CMAKE }} ${{ env.NCNN_CMAKE_OPTIONS }} -DOHOS_ARCH="x86_64" ..
        ${{ env.OHOS_NDK_CMAKE }} --build . -j $(nproc)
        ${{ env.OHOS_NDK_CMAKE }} --build . --target install

    - name: package
      run: |
        mkdir ncnn-package
        mkdir ncnn-package/x86_64
        mkdir ncnn-package/armeabi-v7a
        mkdir ncnn-package/arm64-v8a
        cp -rf build-x86_64/install/* ncnn-package/x86_64/
        cp -rf build-armeabi-v7a/install/* ncnn-package/armeabi-v7a/
        cp -rf build-arm64-v8a/install/* ncnn-package/arm64-v8a/
        zip -r ncnn-package.zip ncnn-package

    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: ncnn-package
        path: ncnn-package.zip
